### ISSUE TITLE
订阅这个博客

### ISSUE THREAD

**Issue by nimoc** [nimoc/blog#15]
## github订阅

<img src="https://cloud.githubusercontent.com/assets/3949015/6850719/bf6f642e-d415-11e4-8096-157ed60f3c3b.png" width="300">
### 订阅

点击本页面右上角的 [Watch](https://github.com/nimojs/nimoc/subscription)  在弹出框中点击 `Watching` 订阅本博客，这样本博客的所有文章更新和评论都会在github首页出现。
![image](https://cloud.githubusercontent.com/assets/3949015/6850925/f12bc470-d416-11e4-9a09-ec3f59041a00.png)
### 收藏

点击 `Star` 收藏本博客，以便在 [stars](https://github.com/stars) 中找到本博客。

你还可以使用此方式订阅 [《Gulp 入门指南》](https://github.com/oggulp-book)

**Comment by JimmyLv** [comment]
#22

**Comment by JimmyLv** [comment]
@nimojs how could you add these reference above?

**Comment by nimojs** [comment]
@JimmyLv 
当我在这些 issues 中链接了这个页面，这里就会显示出所有相关链接

**Comment by JimmyLv** [comment]
@nimojs 哇哈，好酷~！

**Comment by luuman** [comment]
有点意思

**Comment by luuman** [comment]
@JimmyLv 你涉猎挺广的呀！

**Comment by JimmyLv** [comment]
@luuman 经常转呀，哈哈哈

**Comment by dgeibi** [comment]
发现了这个 [gh-feed：使用 RSS 订阅 GitHub Issues 博客 - V2EX](https://www.v2ex.com/t/331849)

**Comment by CatTail** [comment]
@dgeibi 编写了一个输出 Github issues RSS feed 的服务 https://github.com/CatTail/rssify，可以试一下哦。

**Comment by xiaosongxiaosong** [comment]
安利一下自己写的 github 博客阅读工具
IssueReader/IssueReader.github.io#1
欢迎围观使用 😀
