### ISSUE TITLE
给应届IT从业者的一些建议

### ISSUE THREAD

**Issue by nimoc** [nimoc/blog#16]
# 给应届IT从业者的一些建议

我是一名 Web 前端开发程序员。在此处分享一些经验和建议给应届的IT从业者，希望能帮助你们在职业生涯中有一个好的开始（这很重要）。

> 本文源自 [“聚才有道”创业招聘会](http://weibo.com/p/1001603824650017720092) 的一次现场分享。
> 
> 不得不赞一下朝廷能够提供这样有意思的与创业者面对面交流的招聘会。

**目录:**  
1. [请明确你的职位](#hash_position1)
2. [克服紧张](#hash_relax2)
3. [关于加班](#hash_overtime3)
4. [总结](#hash_summarize4)

<a title="请明确你的职位" name="hash_position1"></a>
## 请明确你的职位

有一次面试让我印象深刻。他是一名应届毕业生，来**面试 Web 前端开发**(JavaScript)。

简单的了解他的技能后对话如下：

---

求职者：你们还招 PHP 后端开发吗？

面试官：为什么会这么问？你不是来面试 Web 前端开发的吗？

求职者：嗯.. 我现在想我到底做前端开发还是做PHP后端开发呢。（疑惑状）

面试官：我建议你想清楚选什么，选择好了以后就一直向这方面努力。

求职者：那我可以干一段时间前端再转做后端吗？

面试官：我们建议新员工专注于一件事。基本情况我都已经了解了，如果有需要我们会电话联系你的。

---

相信你已经明白这位求职者已经被拒绝了。如果是企业中意你，会继续介绍一下公司的情况和询问面试者有什么想了解的。

**被拒绝的原因就是面试者不明确自己想做什么。** 当你都不清楚自己想要做什么的时，企业需要承担你随时离职或要求换岗的风险。

因为未来的某一天你可能想清楚自己要做什么了，而现在所做的事并不是你想要的。你有3个选择：
1. 本公司内要求换岗
2. 换一家公司选择合适的岗位
3. 继续在这家公司，但不积极工作。（因为你不喜欢你的岗位）

无论你选择那条路企业都是吃亏的。企业是一个利益团体。企业会规避风险。

比如现在这个场景，我也会规避浪费前端团队培养新人所付出的资源无价值的风险。前端团队花时间去引导你、培养你，结果你忽然不想做前端了。

应届毕业生的这种心态是可以理解的，但请一定想清楚自己要做什么。面对企业的时候一定要明确自己的职位。因为有其他竞争者清楚自己想做什么。

吐槽一件事：

千万千万不要说做几年开发就去转管理，轮不到你！时机合适你自然需要管理你的开发团队，而不是你还开始正式工作就想着要做管理。

技术人员就应该踏踏实实的做好技术，为企业创造价值。管理是一件水到渠成的事。

<a title="克服紧张" name="hash_relax2"></a>
## 克服紧张

有些求职者会表现的很羞涩、说话声音很低、因为紧张表现的很别扭。

这种紧张是正常的。但一定要克服这种紧张，你一紧张就很难讲自己最佳的状态表现出来。而不紧张的人就有更多的机会展示自己。

可以试着改变坐姿或说上一句：不好意思有点紧张。（亲测有效）  
当你有一次进入状态后你就彻底的克服了这这紧张。

<a title="关于加班" name="hash_overtime3"></a>
## 关于加班
- 问：你怎么看待加班？
- 答：我不在乎加班，主要能学到东西就行。

或在简历直接写：我不介意加班，甚至于喜欢加班（为了讨好企业）。

不建议应届毕业生选择问你怎么看待加班的公司。当你没有太多工作经验时就让你每天都处于疲惫状态会让你没有时间学习和思考，这样你会陷入恶性循环。因为没有经验会让你很难找到方向，容易迷失（水平停滞不前）。

不要给企业一种你很”弱势“的信号。你弱势，企业就强势，你就吃亏。好的企业不会选择很不自信的员工。

你可以这样说：“偶尔加班可以接受，加班量大一点希望有加班工资。加班严重占用到私人时间不能接受，因为我需要利用私人时间提高技能（学习）”

<a title="总结" name="hash_summarize4"></a>
## 总结：
- 面对企业的时候一定要明确自己的职位。
- 克服自己的紧张，这样才能更好的展示自己。
- 要自信，不要选择加班严重的公司。

[点此订阅博客](https://github.com/nimojs/blog/issues/15)

若作者显示不是Nimo（被转载了），请访问Github原文进行讨论：[https://github.com/nimojs/blog/issues/16](https://github.com/nimojs/blog/issues/16)

**Comment by lichunqiang** [comment]
:+1:

**Comment by buildjser** [comment]
:+1:

**Comment by bosswee** [comment]
:+1:

**Comment by yuezheng** [comment]
好文。
对于明确要做什么这个问题，对于应届毕业生来说可能真的不是太好确定。
个人技术栈和期望职位不匹配，但当前又急需工作，肯定会做出某种妥协。
我倒是希望企业能考虑毕业生的诉求，通过沟通引导毕业生的职业发展。

**Comment by caiyongmin** [comment]
现在还会有人找工作不知道找什么工作的？😓

**Comment by nimojs** [comment]
@caiyongmin  招聘沙龙里面遇到的一些大学生

**Comment by ColdXu** [comment]
明确自己的方向是很重要的，换位思考一下一个企业不会把精力用在不定人的身上，增加成本。

**Comment by Gaohaoyang** [comment]
很好奇博主在哪里工作？

**Comment by nimojs** [comment]
@Gaohaoyang 上海 二十人的小团队，面试时经常遇到迷茫的应届生

**Comment by JimmyLv** [comment]
请问文章的目录是怎么来的呀？自动生成还是？

**Comment by nimojs** [comment]
@JimmyLv  锚记

**Comment by xuwenzhi** [comment]
有理
