### ISSUE TITLE
使用GitHub接受前端组件开发挑战

### ISSUE THREAD

**Issue by nimoc** [nimoc/blog#22]
# 使用GitHub接受前端组件开发挑战

**[learn-js](https://github.com/nimojs/learn-js)** 是一个**适合前端新手**的 JavaScript 互助学习的项目。接受组件开发的挑战，提交代码让他人评论你的代码以提高。

组件开发的挑战是循序渐进的，每个组件开发挑战都必须掌握必要的知识才可以接受。

---

参与方式： 选择挑战某个组件开发，按阶段完成任务。将自己的代码提交到对应组件中。[GitHub 克隆与请求合并](https://github.com/nimojs/learn-js/blob/gh-pages/fork&pullrequests.md)
## Tab 选项卡

![](https://github.com/nimojs/learn-js/raw/gh-pages/package/tab/tab.png)

[接受挑战](https://github.com/nimojs/learn-js/tree/gh-pages/package/tab)
## Dialog 弹出层

![](https://raw.githubusercontent.com/nimojs/learn-js/gh-pages/package/dialog/dialog.png)

[接受挑战](https://github.com/nimojs/learn-js/tree/gh-pages/package/dialog)

更多挑战将会更新在 [nimojs/learn-js](https://github.com/nimojs/learn-js) 欢迎 [Watch](https://github.com/nimojs/learn-js/subscription) 和 Star 此项目

[点此订阅博客](https://github.com/nimojs/blog/issues/15)
如果作者不是 Nimo（被转载了）,请访问Github原文进行讨论：[https://github.com/nimojs/blog/issues/22](https://github.com/nimojs/blog/issues/22)

**Comment by chenpx976** [comment]
nice

**Comment by ColdXu** [comment]
tab选项做下来，对组件开发理解更深入。一个组件用户在使用时怎么调用，api成功解决了这一问题。

**Comment by PetersonLian** [comment]
感觉吧，能站在一定程度给人指点js的人，一般不会来看别人的js吧？
这个事情是好的，不过，关键在于"指点师"和“指点师的活跃度”。
不如做一个，收徒的平台会更好点。

**Comment by nimojs** [comment]
@PetersonLian 
对，最终一年下来互动不多。关键是 **组件开发的挑战是循序渐进的**和**可以参考他人代码**。需要这个项目的人一般都是想做一些JS的组件，但是不知道如何开始，遇到问题没有参考的代码。

**Comment by PetersonLian** [comment]
@nimojs 我只是粗粗看了一下这个项目想到了可能是个问题的地方。我没有玩过这个挑战。不过，应该有人能在这个形式上获得一些帮助吧。
你也是极好，精神上绝对支持你们做这些事情。
